services:
  postgres:
    image: postgres:13.3-alpine
    container_name: test
    restart: unless-stopped
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: "test_task"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./dbroot:/root